const IMAGE_UPLOAD_URL_GENERATED = 'Image upload url generated';
const IMAGE_MAX_SIZE_BYTES = 52428800; //50mb
const IMAGE_PRESIGNED_URL_EXPIRED_SECONDS = 300;
const IMAGE_PRESIGNED_URL_ACL = '';
const IMAGE_PRESIGNED_URL_FILE_PATH = '/profile/images/';

const PROFILE_UPDATED = 'Profile updated successfully';

const DB_CONNECTION_TIMEOUT_MILLIS = 2000;
const DB_MAX_CLIENTS = 20;
const DB_IDLE_TIMEOUT_MILLIS = 30000;

export {
  IMAGE_UPLOAD_URL_GENERATED, PROFILE_UPDATED, DB_CONNECTION_TIMEOUT_MILLIS, DB_IDLE_TIMEOUT_MILLIS, DB_MAX_CLIENTS,
  IMAGE_MAX_SIZE_BYTES, IMAGE_PRESIGNED_URL_EXPIRED_SECONDS, IMAGE_PRESIGNED_URL_ACL, IMAGE_PRESIGNED_URL_FILE_PATH
}